[package]
name = "icechat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automerge = "0.3.0"
autosurgeon = { version = "0.3.0", features = ["uuid"] }
uuid = "1.3.0"
