//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "channel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub conversation: i32,
    pub peer: i32,
    pub sync_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::Conversation",
        to = "super::conversation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Conversation,
    #[sea_orm(has_many = "super::initial_sync::Entity")]
    InitialSync,
    #[sea_orm(
        belongs_to = "super::key::Entity",
        from = "Column::Peer",
        to = "super::key::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Key,
    #[sea_orm(has_many = "super::sync::Entity")]
    Sync,
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl Related<super::initial_sync::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InitialSync.def()
    }
}

impl Related<super::key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Key.def()
    }
}

impl Related<super::sync::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sync.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
