//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid0: i32,
    pub uuid1: i32,
    pub uuid2: i32,
    pub uuid3: i32,
    pub status: i32,
    pub from: i32,
    pub conversation: i32,
    pub text: String,
    pub crdt_generation: i32,
    pub crdt_author: i32,
    pub status_crdt_generation: i32,
    pub status_crdt_author: i32,
    pub crdt_sequence: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contact::Entity",
        from = "Column::From",
        to = "super::contact::Column::Key",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Contact,
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::Conversation",
        to = "super::conversation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Conversation,
    #[sea_orm(
        belongs_to = "super::key::Entity",
        from = "Column::From",
        to = "super::key::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Key,
}

impl Related<super::contact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contact.def()
    }
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl Related<super::key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Key.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
